server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wuhan_gis
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
      schema-locations: classpath:setup.sql

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.icity.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
